name: Valefor.com
baseurl: /
url: http://www.valefor.com
encoding: UTF-8
markdown: redcarpet
pygments: false
gems:
  - jekyll-sitemap
exclude:
  - .bundle
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - node_modules
  - package.json
  - README.md
